### ISSUE TITLE
Not working fallback for `showgit` option?

### ISSUE THREAD

**Issue by Cs137** [wannesm/adsphd#121]
Quite some time ago I started using your approach to show a git commit's hash in some of my documents. However, I do not understand the fallback if no shell escape is enabled. You check for a version file and handle it like the content of the file which cashed the commit hash. This is implemented in the main class file beginning with [line 341](https://github.com/wannesm/adsphd/blob/master/adsphd.cls#L341):

```tex
    \IfFileExists{VERSION}{%
      \adsphd@showgittrue
      \openin1=VERSION
      \read1 to \gitdescribe
      \closein2
      \message{Warning: Fallback on VERSION file for print git information. (Create such a file with a git-hook)}
    }{%
      \adsphd@showgitfalse
      \message{Warning: Also no VERSION file found. Git information will not be shown.}
    }
```

Since the file-path is represented by the string `VERSION`, the quoted lines are in my opinion without any functionality and the fallback will not work. 

I would appreciate if someone could confirm my thoughts, or would let me know what I missed.

**Comment by wannesm** [comment]
I'm not sure I understand what the problem is with this snippet. The relative file path 'VERSION' is hardcoded in the latex code. If it exist, the contents is stored in \gitdescribe. If it does not exist, the showgit boolean is set to false.

I tested it and the snippet works, but I noticed that the git hash was not shown in the pdf when the hash was read from the VERSION file later in the code. So I did fix that part of the code in commit c0c6748d64abdb35c93adda35ac18b0dcd6c1562 .

**Comment by Cs137** [comment]
Thanks for your response, @wannesm. The point I did not get is that `VERSION` is a string and no command/macro. According to my understanding, it will only work if the file is called `VERISON`.

**Comment by wannesm** [comment]
Correct, it will only work if the file is called `VERSION`.

**Comment by Cs137** [comment]
Thanks for the clarification. That was the actual reason for my confusion and let to the creation of this issue ;-)
