### ISSUE TITLE
cover page

### ISSUE THREAD

**Issue by martatuzza** [wannesm/adsphd#59]
I have some troubles creating the cover page using the comand make cover. 
I get the following error. 
Class adsphd Error: Unsupported value '' for class option 'faculty'.

See the adsphd class documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.393 ...r class option 'faculty'}{\MessageBreak}}

**Comment by jespercockx** [comment]
Now, I realize that this issue is quite old and you probably already finished, but below some comments for other people having the same problem.

I had the same problem with generating the cover page. You should add the options for the faculty, department, and phddegree you have in the thesis.tex to the cover.tex file as well. This has been a problem since these options were added (3d379eb3e268eba65a1432c49bcf66aae4cd5a8c).

If you do that, you'll notice that a pdf will be build, however it will be mostly blank aside from the cut lines. This is another problem which was introduced by 9fe89d153800cc64a7f2485ea576894e8bc47123. If you revert this commit (by running `git revert 9fe89d153800cc64a7f2485ea576894e8bc47123`) the problem should be fixed.

**Comment by wannesm** [comment]
Thanks Jesper, I've fixed it based on your feedback.

The run.py fix is automatically copying the settings from thesis.tex but the makefile fix is a bit cumbersome for the user. I'm happy to accept pull requests with improvements :-)
